# Generated by Django 2.1 on 2018-08-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.TextField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
